ALTER TABLE selection_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE selection_evaluations ENABLE ROW LEVEL SECURITY;
ALTER TABLE symbol_cooldowns ENABLE ROW LEVEL SECURITY;
ALTER TABLE pattern_library_excluded ENABLE ROW LEVEL SECURITY;
ALTER TABLE mr_gate_blocked ENABLE ROW LEVEL SECURITY;
