name: Keepalive

on:
  schedule:
    - cron: "0 12 * * 1"  # Every Monday noon UTC
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          time_elapsed: 50
